spring:
  datasource:
    url: "jdbc:mariadb://localhost:3306/mosk_manager"
    username: "mosk_manager"
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
    open-in-view: true

server:
  port: 9090

logging:
  level:
    mosk.product.manager: debug